name: build
on: [push, pull_request]
jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: "recursive"
            - uses: abel0b/setup-premake@v2.3
              with:
                version: '5.0.0-beta2'
            - run: 'sudo apt install git build-essential libxi-dev libxinerama-dev libxrandr-dev libxcursor-dev libgl1-mesa-dev libx11-dev libgtk-3-dev'
            - run: 'sh build_linux.sh'
              working-directory: './Dependencies/'